export const  GET_ITEM_REQUEST = "GET_ITEM_REQUEST";
export const  GET_ITEM_SUCSESS = "GET_ITEM_SUCSESS";
export const  GET_ITEM_RFAILURE = "GET_ITEM_RFAILURE";

export const  POST_ITEM_REQUEST = "POST_ITEM_REQUEST";
export const  POST_ITEM_SUCSESS = "POST_ITEM_SUCSESS";
export const  POST_ITEM_RFAILURE = "POST_ITEM_RFAILURE";

export const  PUT_ITEM_REQUEST = "PUT_ITEM_REQUEST";
export const  PUT_ITEM_SUCSESS = "PUT_ITEM_SUCSESS";
export const  PUT_ITEM_RFAILURE = "PUT_ITEM_RFAILURE";